### ISSUE TITLE
Crash while starting up emission on android

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-data-collection#124]
I found this using logcat

```
E/AndroidRuntime( 2497): java.lang.RuntimeException: Unable to start receiver edu.berkeley.eecs.emission.cordova.tracker.location.TripDiaryStateMachineReceiver: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2431)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.access$1500(ActivityThread.java:141)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1332)
E/AndroidRuntime( 2497): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2497): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime( 2497): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2497): 	at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime( 2497): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime( 2497): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime( 2497): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 2497): Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
E/AndroidRuntime( 2497): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
E/AndroidRuntime( 2497): 	at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:598)
E/AndroidRuntime( 2497): 	at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
E/AndroidRuntime( 2497): 	at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
E/AndroidRuntime( 2497): 	at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:813)
E/AndroidRuntime( 2497): 	at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:801)
E/AndroidRuntime( 2497): 	at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:862)
E/AndroidRuntime( 2497): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:242)
E/AndroidRuntime( 2497): 	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
E/AndroidRuntime( 2497): 	at edu.berkeley.eecs.emission.cordova.usercache.BuiltinUserCache.getDocument(BuiltinUserCache.java:151)
E/AndroidRuntime( 2497): 	at edu.berkeley.eecs.emission.cordova.tracker.ConfigManager.isConsented(ConfigManager.java:44)
E/AndroidRuntime( 2497): 	at edu.berkeley.eecs.emission.cordova.tracker.location.TripDiaryStateMachineReceiver.onReceive(TripDiaryStateMachineReceiver.java:86)
E/AndroidRuntime( 2497): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2424)
E/AndroidRuntime( 2497): 	... 10 more
```

**Comment by shankari** [comment]
This happened right after boot. I wonder if this is the reason for 
https://github.com/e-mission/e-mission-server/issues/332

**Comment by shankari** [comment]
Ran into this again on the trip to Gilroy Gardens when my location tracking was turned off.

```
07-24 19:53:44.595 25057 25135 E SQLiteLog: (5) database is locked
07-24 19:53:44.783 25057 25135 E SQLiteDatabase: Failed to open database '/data/user/0/ed
u.berkeley.eecs.emission/databases/userCacheDB'.
07-24 19:53:44.783 25057 25135 E SQLiteDatabase: android.database.sqlite.SQLiteDatabaseLo
ckedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
07-24 19:53:44.783 25057 25135 E SQLiteDatabase:        at android.database.sqlite.SQLite
Connection.nativePrepareStatement(Native Method)
07-24 19:53:44.783 25057 25135 E SQLiteDatabase:        at android.database.sqlite.SQLite
Connection.acquirePreparedStatement(SQLiteConnection.java:889)
07-24 19:53:44.783 25057 25135 E SQLiteDatabase:        at android.database.sqlite.SQLite
Connection.executeForString(SQLiteConnection.java:634)
```

[bugreport-2016-07-24-19-54-46.txt.gz](https://github.com/e-mission/e-mission-data-collection/files/471075/bugreport-2016-07-24-19-54-46.txt.gz)

**Comment by shankari** [comment]
Concurrency appears to be between

```
07-24 19:53:43.251 25057 25123 V executeSqlBatch: SQLitePlugin.executeSql[Batch](): Error
=sqlite3_prepare_v2 failure: database is locked
```

```
07-24 19:53:44.783 25057 25135 E SQLiteDatabase:        at edu.berkeley.eecs.emission.cordova.usercache.BuiltinUserCache.putValue(BuiltinUserCache.java:111)
07-24 19:53:44.783 25057 25135 E SQLiteDatabase:        at edu.berkeley.eecs.emission.cordova.usercache.BuiltinUserCache.putSensorData(BuiltinUserCache.java:97)
07-24 19:53:44.783 25057 25135 E SQLiteDatabase:        at edu.berkeley.eecs.emission.cordova.tracker.location.LocationChangeIntentService.onHandleIntent(LocationChangeIntentService.java:79)
```

```
07-24 19:53:45.447 25057 25123 V executeSqlBatch: SQLitePlugin.executeSql[Batch](): Error=sqlite3_prepare_v2 failure: database is locked
```

And the after that, the database gets malformed

```
07-24 19:54:34.673 25168 25350 W System.err: java.sql.SQLException: sqlite3_step failure:
 database disk image is malformed
07-24 19:54:34.705 25168 25350 V executeSqlBatch: SQLitePlugin.executeSql[Batch](): Error
=sqlite3_step failure: database disk image is malformed
```

```
07-24 19:54:34.705 25168 25350 W System.err: java.sql.SQLException: sqlite3_step failure: database disk image is malformed
...
07-24 19:54:34.712 25168 25350 V executeSqlBatch: SQLitePlugin.executeSql[Batch](): Error=sqlite3_step failure: database disk image is malformed
```

**Comment by shankari** [comment]
But the next invocation seems fine.

```
07-24 19:54:47.494 25168 25402 D LocationChangeIntentService: Finding points in the range 1.469414977424E9 < 2131099784 < 1.469415287424E9
07-24 19:54:47.494 25168 25402 I System.out: About to execute query SELECT data FROM userCache WHERE key = 'background/filtered_location' AND write_ts >= 1.469414977424E9 AND write_ts <= 1.469415287424E9 ORDER BY write_ts DESC
07-24 19:54:47.658 25168 25402 I System.out: data = {"fmt_time":"Jul 24, 2016 7:54:13 PM","filter":"time","sensed_speed":0.0,"ts":1.469415253979E9,"altitude":0.0,"latitude":37.3885014,"longitude":-121.8721044,"elapsedRealtimeNanos":181294345000000,"accuracy":78.849,"bearing":0.0}
```

**Comment by shankari** [comment]
I fixed this by migrating all connections to the usercache native code.

https://github.com/e-mission/cordova-usercache/pull/20 
and
https://github.com/e-mission/cordova-usercache/pull/21

**Comment by shankari** [comment]
However, it turns out that this was still not fixed. I ran into a similar crash again today.

```
10-20 10:46:54.558  15410-16215/? E/SQLiteDatabase﹕ Error inserting data={"mVersionCode":1,"zzaKM":4,"zzaKN":43} timezone=America/Los_Angeles type=sensor-data write_ts=1.476985611892E9 key=background/motion_activity
    android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
            at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
            at edu.berkeley.eecs.emission.cordova.usercache.BuiltinUserCache.putValue(BuiltinUserCache.java:134)
            at edu.berkeley.eecs.emission.cordova.usercache.BuiltinUserCache.putSensorData(BuiltinUserCache.java:97)
            at edu.berkeley.eecs.emission.cordova.tracker.location.ActivityRecognitionChangeIntentService.onHandleIntent(ActivityRecognitionChangeIntentService.java:51)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

[usercache_still_locked.gz](https://github.com/e-mission/e-mission-data-collection/files/543765/usercache_still_locked.gz)

**Comment by shankari** [comment]
This appears to be because we create multiple handlers for the cache, one for each thread.
So concurrent access leads to logs.

Recommendation from stackoverflow is to make it be single-threaded with a singleton pattern for access.

http://stackoverflow.com/questions/7930139/android-database-locked
and 
http://stackoverflow.com/questions/10450977/android-sqlite-with-multi-thread
